### ISSUE TITLE
Syntax Map Improvements

### ISSUE THREAD

**Issue by brian-ruf** [usnistgov/metaschema#105]
# User Story:

s an OSCAL implementer, when reviewing the OSCAL syntax maps it would be helpful to use background and border shading similar to what was used in the original version of the generated maps. 

In the original version, when hovering over an assembly the box would highlight in a very visible and obvious way. With the new document map generation, the highlights are too subtle and easy to miss. 

## Goals:

* Improve the visual clues when hovering over an assembly to better match the hover behavior and color selection in the original document maps.

## Dependencies:

None.

## Acceptance Criteria

- [ ] All [website](https://pages.nist.gov/metaschema) and readme documentation affected by the changes in this issue have been updated. Changes to the website can be made in the docs/content directory of your branch.
- [ ] A Pull Request (PR) is submitted that fully addresses the goals of this User Story. This issue is referenced in the PR.
- [ ] The CI-CD build process runs without any reported errors on the PR. This can be confirmed by reviewing that all checks have passed in the PR.

**Comment by wendellpiez** [comment]
On the models maps the border (on an element or object) now goes darker on hover.

Unfortunately CSS doesn't let us do much more than this. Setting background color to respond to hover results only in the entire containing structure (entire tree) receiving the new background - i.e. background changes not only on the innermost hovered element, but on all of them, because the containing element is also hovered when the contained element is (at any level). The logic we apparently need ('shift the background when hovered but not when a descendant is hovered') is not expressible in CSS (is it?).

Ideas for further enhancement are certainly welcome!
