### ISSUE TITLE
Resolve Syntax Documentation Generation Issues

### ISSUE THREAD

**Issue by brian-ruf** [usnistgov/metaschema#113]
# Describe the bug

There are several small issues where the syntax documentation is not being generated as intended. A few are listed below. Others may be added as comments. These include:
- In some instances, allowed values defined in the metaschema are not enumerated in the syntax documentation.
- In the document map, so assemblies are not clickable. To some degree this may be by design; however, its application is inconsistent.
- In "choice" children, indenting does not align where an assembly is not expanded to avoid recursion.

# Who is the bug affecting?

Users of the OSCAL syntax documentation.

# What is affected by this bug?

Syntax information is more difficult to reach, or is unavailable.
Documentation is more difficult to use.

# When does this occur?

When the documentation is generated by the CI/CD pipeline.

# How do we replicate the issue?

**Allowed Value Issue:**
NOTE: There is one identified source of this, but analysis should be performed to ensure there are not more instances.

The assessment-common metaschema correctly includes the following in the model for `//objective-status`:
```
         <define-field name="status" as-type="NCName" min-occurs="1" max-occurs="1">
            <formal-name>Implementation Status</formal-name>
            <description>A brief indication as to whether the objective is satisfied or not within a given system.</description>
            <!-- CHANGED: removed @system flag -->
            <constraint>
               <allowed-values target=".">
                  <enum value="satisfied">The objective has been completely satisfied.</enum>
                  <!-- CHANGED "other-than-satisfied" to "not-satisfied" -->
                  <enum value="not-satisfied">The objective has not been completely satisfied, but may be partially satisfied.</enum>
               </allowed-values>
            </constraint>
         </define-field>
```

When you view the [documentation](https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/xml-schema/##local_objective-status-status_def-h3), the description is present; however, it does not enumerate the "satisfied" or "not-satisfied" allowed values.

**Unclickable Assemblies (Example 1):**
- Open any OSCAL model map.
- Expand metadata.
- Observe `revisions` is the only metadata assembly _without_ a hyperlink, Even some fields have hyperlinks.

**Unclickable Assemblies (Example 2):**
- In the [Assessment Plan Model Map](https://pages.nist.gov/OSCAL/documentation/schema/assessment-layer/assessment-plan/xml-model-map/)
- Observe `local-definitions` and `terms-and-conditions` do not have hyperlinks.

**Unclickable Assemblies (Example 3):**
- In the [Assessment Results Model Map](https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/xml-model-map/)
- Observe `local-definitions` does not have a hyperlink.
- Expand `result`
- Observe `local-definitions`,  `attestation`, and `assessment-log` do not have hyperlinks.

**Indentation issue:**
- Visit the [Catalog Model Map](https://pages.nist.gov/OSCAL/documentation/schema/catalog-layer/catalog/xml-model-map/):
- Expand `group`
- After `part` view the content under _A choice:_

# Expected behavior (i.e. solution)

**Allowed Value Issue:**
All enumerated allowed values should be included in the generated documentation no matter where or how they are defined in the metaschema (assuming correct metaschema syntax).

**Unclickable Assemblies:**
There needs to be greater consistency regarding assemblies that have hyperlinks and those that do not. 
At a minimum, all top-level assemblies should have hyperlinks, as should any complex assembly.
NOTE: "complex" is a subjective term. Perhaps this can minimally mean any assembly with child assemblies or having more than eight children. (many assemblies have `title`, `description`, `part`, `annotation`, `link`, and `remarks` - six children - so the threshold should be seven or higher.)

# Other Comments

Consider working on this issue as the same time as issue #105

**Comment by brianrufgsa** [comment]
# Another Documentation Generation Bug

## Erroneous Allowed Values for `//metadata/prop`

The list of allowed values is incorrect.

## Reproduce:
- Visit Any [Model Map](https://pages.nist.gov/OSCAL/documentation/schema/assessment-results-layer/assessment-results/xml-schema/##local_metadata-revision-property_ref-h3):
- Find the `metadata` entry
- Find the `prop` entry beneath it
- At the bottom of the entry, expand `Model from prop global definition`
- Find the `name` entry
- Observe an extensive list of incorrectly located Allowed Values

NOTE: This is the case both for `//metadata/prop` and `//metadata/revisions/revision/prop`

## Expected Behavior:
Only the allowed values for a `prop` field's `name` should appear here based on the context.

**Comment by brianrufgsa** [comment]
# Another documentation Generation Bug

## No values presented for `/system-security-plan/system-implementation/component/@type`

The documentation should display values, such as "this-system", "interconnection", "software", "hardware", etc.

## Reproduce:
- Visit the [SSP Component documentation](https://pages.nist.gov/OSCAL/documentation/schema/implementation-layer/ssp/xml-schema/#global_system-component).
- Find `type`
- Observe no values listed.

## Expected Behavior:
The allowed values for `type` defined in the metaschema should be presented.

## Additional notes:
- These allowed values are spread out. 
- Some are in `src/metaschema/shared-constraints/allowed-values-component-type.ent`
- Others are in `src/metaschema/oscal_implementation-common_metaschema.xml`
- The syntax is generated based on `src/metaschema/oscal_ssp_metaschema.xml`, which imports the common metaschema.
I suspect it's the complexity of this interaction creating this issue.

**Comment by wendellpiez** [comment]
This Issue duplicates a number of other issues being tracked: usnistgov/OSCAL#847 usnistgov/OSCAL#848 usnistgov/OSCAL#849

Missing values in documentation appear to be linked to #121.

I suggest we either close this Issue as duplicating those others, or return after they are done to review for coverage.

**Comment by wendellpiez** [comment]
Opting to leave this here to review when other points on #120 have been addressed as well.
