### ISSUE TITLE
Model Reference Documentation: Allowed Value Documentation Strings Propagated into XML Model Outlines

### ISSUE THREAD

**Issue by aj-stein-nist** [usnistgov/metaschema#241]
# Describe the bug

Given `enum`s for an allowed value with documentation strings in the `<enum>description</enum>` text value like `description` here, such doc strings are not being properly filtered out or styled. For a final node terminating the branch of the tree in the XML outline, blocks of documentation are being generated from groups of these `allow-values` `enums`. Currently, this occurs in OSCAL's `main` branch at https://github.com/usnistgov/OSCAL/commit/6a527ba0c107c29479b2b0e5dfeaecffe3eaf836.

# Who is the bug affecting?

NIST OSCAL developers and community tool developers working with modified model changes they want reflected in generated documentation for the models such as the XML outlines.

# What is affected by this bug?

Model reference documentation

# When does this occur?

Consistently

# How do we replicate the issue?

Visit the [OSCAL mapping page](https://pages.nist.gov/OSCAL/reference/develop/mapping/xml-outline/) for an example.

![image](https://user-images.githubusercontent.com/94922603/191655517-9528ee5f-da4a-49d2-bae9-45b88bdbf52d.png)

# Expected behavior (i.e. solution)

The `allow-values` `enums` documentation strings are filtered out and not presented in the OSCAL Mapping Model XML Outline.

# Other Comments

**Comment by wendellpiez** [comment]
Now addressed in #242 and ready to test.

Found an unrelated bug in the docs, file `oscal_mapping-common_metaschema.xml`: at `/*/define-assembly[@name='map']/model/define-field[@name='relationship']/constraint/allowed-values/enum[@value='equivalent-to']` the text shows a noun/verb agreement issue:

> The effective requirements of the source is equivalent in semantic meaning to the effective requirements of the target

(Should be *are*. Actually "equivalent in meaning" should do the trick, since "semantic" adds no semantic in this context.)
