### ISSUE TITLE
Request to remove dashes from property names

### ISSUE THREAD

**Issue by smichelotti** [usnistgov/metaschema#35]
# User Story:

As a (JavaScript) developer I would like the ability to have more developer-friendly property names without dashes.

## Goals:

When property names have dashes in the name (e.g., `control-id`, `id-selectors`), this is certainly valid JSON, but they are unnatural for programming languages like JavaScript, C#, etc. The work-around for this in JavaScript is to use square bracket syntax:

```JavaScript
include['id-selectors'][0]
```
but more developer-friendly would be:
```JavaScript
include.idselectors[0]
```
or even camel-case:
```JavaScript
include.idSelectors[0]
```
Request to please consider an alternative to property names with dashes.

## Acceptance Criteria

- [ ] No square bracket syntax is required when working with property names in languages such as JavaScript.

**Comment by anweiss** [comment]
@wendellpiez I wonder if providing something along the lines of idiomatic delineators in the metaschema would be beneficial at all ... style guide constraints, per se ...  such as support alternative casing for property names as @smichelotti is alluding to

The follow up question to this would then need to be whether or not the metaschema should support such constraints or if that should be left up to the developers to decide based on the programming languages and recommended style guidance they may be using; especially since programming languages often use multiple styles of casing (camel vs. pascal vs. snake, etc) and other idioms

**Comment by david-waltermire-nist** [comment]
There are ways to address this in any programming language, e.g., `include['id-selectors'][0]`. In many cases, a programmer will need to check for existence of the node, which also requires some work on behalf of the developer.

Addressing this would be a big lift to both adjust the Metaschema syntax and all current instances. It would also require changes to OSCAL syntax, which would be a backwards compatibility breaking change. This would require a major version release of both Metaschema and OSCAL to fix.

Given the lack of support for this issue, the emergence of some tooling already in this space, and the degree of disruption that addressing this issue will cause, we should continue to move forward as-is.
